pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  push:
    image: plugins/docker
    username: juanforo
    password: elpass
    repo: juanforo/movie-analyst-api
    tags: "${DRONE_COMMIT_SHA}"
services:
  api:
    image: juanforo/movie-analyst-api
