pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  push:
    image: plugins/docker
    username: "${USER}" 
    password: "${PASS}"
    email: juanforo94@hotmail.com
    repo: juanforo/movie-analyst-api
    tags: "${DRONE_COMMIT_SHA}"
  deploy:
    image: docker
    command: docker run -d -p 3000:3000 juanforo/movie-analyst-api
