pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  deploy:
    image: plugins/docker
    username: juanforo
    password: j9u4a0n3
    email: juanforo94@hotmail.com
    repo: juanforo/movie-analyst-api
    tags: "${DRONE_COMMIT_SHA}"
