pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  push:
    image: plugins/docker
    username: juanforo
    password: j9u4a0n3
    email: juanforo94@hotmail.com
    repo: juanforo/movie-analyst-api
    tags: "${DRONE_COMMIT_SHA}"
  deploy:
    image: appleboy/drone-ssh
    host: 34.201.160.191
    username: docker
    key: -----BEGIN RSA PRIVATE KEY-----MIIEowIBAAKCAQEAzsRcY8rpOUEY5fUKGL6iK6JJAuAJl+xDLzAoZT+sJ9MkvX9CHhRiBYc2aeGitApwJYdzwGUmaJC8rQJJe7Z6cSQeULuwtlvbZgeP1438ZLTfrwx6dwWcUsHQY8KfMRdjl+/F3aim6Pu5fagMwKCsMfDutyZI21PPvUeLIQRuOT8rP8s+TJXSNcXToY13XnQZTjcjMUgJMTFJaH7SbeNpPyBHuQhYw3ccbEx37wn/57RnMrvSAT2xWX43qEn9x8mgYt7QQGwgE+qOg3hrzWHsLBsIRzNWevvFck73OzeirJ5xLLWjb/5tJUGaUNuOvE2R18+fCLfrfwHNU5PO+5ddgwIDAQABAoIBAD9yRZ9hjjtBXHCDxntdU8nr3FeDg64Yk20Ra/PVm/AEfEuhlxo/yuxDV1EaKaDxawQ5Ei3BXA3OC/dSslXB4sSA/sRrM4hhm2stetf7+6yzS8gdHh8Tm6pRSq6x88NOmALxUlf3/m+TfpGuVWtuYihY9AdDOiwDBcXhBDI3d9Mcn6Rfu3i8tshOqzoA09Pn575OiCqeWh++x9v1c66/UbLLjq25V3mgGKfZfXI83JmY2Glsxu614Ahk0+t8o/6/zhwi8dKTB4W2KX3xMsZh3ytiPSk5qzlsALKkG0rAGJLx1pM1V9Ka9Ugg//kuVS8K5touWqRRfX3Uz4R2SUCfhpECgYEA9KWIsZFGw2O0HV0Y0gSiqg+9Va+3OfoJi32hZDNShi7KVxW2kMP8Azqwsy0FZWi5cLW4QhdOh5qn6Vlhy4rBldF8vAq36W2lrxkq7XbdVmD9IaoiTugwV5QnN+s7LFLa4cs6e03sSh9SKfhHFwVY6FCeJT3nnndRaotipJBZZVcCgYEA2FzOu/q6LJH+UUJXfxM/GFiyMMkM99+wUG4esGWOGy0W6GXo5Xfi8jCWlW5nTReEn/JK+QtnYCZlt8jt9PBFqz8byNQ09pu1CLXB3KWjpul4/VsqYconirSrtQqKB0FrPtzwAUGhmu0BpDSm6+V+1bZ7h0CDcI4qK1BhQ2IxobUCgYAn/MaS/4Ppe+p8wjLEYS2VTm1MDCSOvWfB/Q7cKedbN1qrUUk98ErI3Fb1cm5nXO6ylYFAjD6xu32mjo2Fj3CE5HDW64mUBfAG5r41gjA7Zi75ya1B6IG+TuD6KuDJJeHQ9j7g2KO+mc/8PDCieqVFk6fFvpCVPjt4hr/g1hdGkQKBgQC6vvAZRAGpMqGllXNb1UriQrwaa43r7ICMC2AltKIBRtu83ykz1lRl4hY3CEHVQnVQcJrRdkxVqw6koKLyhOg9NI1QvAiyyhZpXCflwHoOOPobA7MDEK8sg2CpNF2KgaaFbcEh9Hn99I80IdXpSf49i/H2/XH1ll9DX29z768S+QKBgE24uN1I7ZvJoRZ+83fslNbP+sC99VZzLeiRuaYhdHCNpKQiVAAnvl/A3nUf8jDT/sq2DQb4VDBc25rWfmXciFqdFm4gOUMWu621r9wTrveU736KGHUt2CvG9f7GPE4tacPEaQzB9+muxrp0Gyz385XuEPm/aLgTmIQRYZwXqDgO-----END RSA PRIVATE KEY-----
    port: 22
    script:
      - echo hello
      - echo world 
