pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  build:
    image: docker
    privileged: true
    commands:
      - docker build --rm -t juanforo/movie-analyst-api .
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
  deploy:
    image: peloton/drone-ecs
    access_key: AKIAJ6MXUZVBKH67ZMKQ
    secret_key: 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
    service: backend
    region: us-east-1
    family: backend:1
    image_name: 969709445374.dkr.ecr.us-east-1.amazonaws.com/movie-analyst-api
    image_tag: ${DRONE_COMMIT_SHA:0:8}
    port_mappings:
      - 3000 3000 
    memory: 128
        #  notify:
        #    image: plugins/slack
        #    channel: developers
        #    username: drone
