pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  build:
    image: plugins/docker
  ecs:
    image: peloton/drone-ecs
    access_key: AKIAJ6MXUZVBKH67ZMKQ
    secret_key: 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
    service: backend
    region: us-east-1
    family: my-ecs-task
    image_name: "969709445374.dkr.ecr.us-east-1.amazonaws.com/movie-analyst-api"
    image_tag: latest
