pipeline:
  test:
    image: node:6
    commands:
      - npm install
      - npm test
  push:
    image: plugins/docker
    repo: juanforo/movie-analyst-api
    tags: "${DRONE_COMMIT_SHA}"
    secrets: [ usuario, contra ]
  deploy:
    image: docker
    command: docker run -d -p 3000:3000 juanforo/movie-analyst-api
