pipeline:
  build:
    image: node:6
    commands:
      - npm install
      - npm test

        #  notify:
        #    image: plugins/slack
        #    channel: developers
        #    username: drone
